FROM docker.vpclub.cn/hidevopsio/s2i-java

RUN mkdir ${HOME}/vpclub/ && chmod 755 ${HOME}/vpclub

WORKDIR ${HOME}/vpclub

COPY pkg-demo ${HOME}/vpclub/pkg-demo

COPY config/ ${HOME}/vpclub/config/

ENV MAVEN_MIRROR_URL http://nexus.vpclub.cn/repository/maven-public/
ENV MAVEN_CLEAR_REPO false

EXPOSE 7575
EXPOSE 8080

CMD ["./pkg-demo"]